<?php

return [
    'items' => [
        // --- Global context (no tenant) ---
        [
            'key' => 'dashboard',
            'label' => 'Dashboard',
            'route' => 'dashboard',
            'icon' => 'dashboard',
            'roles' => ['super_admin'],
            'context' => 'global',
        ],
        [
            'key' => 'new_tenant',
            'label' => 'New tenant',
            'route' => 'tenants.create',
            'icon' => 'plus',
            'roles' => ['super_admin'],
            'context' => 'global',
        ],
        [
            'key' => 'tenants',
            'label' => 'Tenants',
            'route' => 'tenants.index',
            'icon' => 'building',
            'roles' => ['super_admin'],
            'context' => 'global',
        ],
        [
            'key' => 'plans',
            'label' => 'Plans',
            'route' => 'plans.index',
            'icon' => 'clipboard',
            'roles' => ['super_admin'],
            'context' => 'global',
        ],
        [
            'key' => 'profile',
            'label' => 'Profile',
            'route' => 'profile.show',
            'icon' => 'user',
            'roles' => ['super_admin'],
            'context' => 'global',
        ],

        // --- Tenant context (/t/{slug}) ---
        [
            'key' => 'dashboard',
            'label' => 'Dashboard',
            'route' => 'tenant.dashboard',
            'icon' => 'dashboard',
            'roles' => ['super_admin', 'builder_admin', 'manager', 'sales_exec', 'viewer'],
            'context' => 'tenant',
        ],
        [
            'key' => 'projects',
            'label' => 'Projects',
            'route' => 'tenant.projects.index',
            'icon' => 'folder',
            'roles' => ['super_admin', 'builder_admin', 'manager'],
            'context' => 'tenant',
        ],
        [
            'key' => 'leads',
            'label' => 'Leads',
            'route' => 'tenant.leads.index',
            'icon' => 'leads',
            'roles' => ['super_admin', 'builder_admin', 'manager', 'sales_exec', 'viewer'],
            'context' => 'tenant',
        ],
        [
            'key' => 'channel_partners',
            'label' => 'Channel Partners',
            'route' => 'tenant.cp-applications.index',
            'icon' => 'users',
            'roles' => ['super_admin', 'builder_admin', 'manager'],
            'context' => 'tenant',
        ],
        [
            'key' => 'managers',
            'label' => 'Managers',
            'route' => 'tenant.managers.index',
            'icon' => 'user-plus',
            'roles' => ['super_admin', 'builder_admin'],
            'context' => 'tenant',
        ],
        [
            'key' => 'forms',
            'label' => 'Forms',
            'route' => 'tenant.forms.index',
            'icon' => 'form',
            'roles' => ['super_admin', 'builder_admin'],
            'context' => 'tenant',
        ],
        [
            'key' => 'locks',
            'label' => 'Locks',
            'route' => 'tenant.locks.index',
            'icon' => 'lock',
            'roles' => ['super_admin', 'builder_admin', 'manager', 'sales_exec'],
            'context' => 'tenant',
        ],
        [
            'key' => 'visits',
            'label' => 'Visits',
            'route' => 'tenant.visits.index',
            'icon' => 'calendar',
            'roles' => ['super_admin', 'builder_admin', 'manager', 'sales_exec'],
            'context' => 'tenant',
        ],
        [
            'key' => 'reports',
            'label' => 'Reports',
            'route' => 'tenant.reports.index',
            'icon' => 'chart',
            'roles' => ['super_admin', 'builder_admin', 'manager', 'viewer'],
            'context' => 'tenant',
        ],
        [
            'key' => 'settings',
            'label' => 'Settings',
            'route' => 'tenant.settings',
            'icon' => 'cog',
            'roles' => ['super_admin', 'builder_admin'],
            'context' => 'tenant',
        ],
        [
            'key' => 'profile',
            'label' => 'Profile',
            'route' => 'tenant.profile',
            'icon' => 'user',
            'roles' => ['super_admin', 'builder_admin', 'manager', 'sales_exec', 'viewer'],
            'context' => 'tenant',
        ],

        // --- Channel partner context ---
        [
            'key' => 'dashboard',
            'label' => 'Dashboard',
            'route' => 'cp.dashboard',
            'icon' => 'dashboard',
            'roles' => ['channel_partner'],
            'context' => 'channel_partner',
        ],
        [
            'key' => 'my_leads',
            'label' => 'My Leads',
            'route' => 'cp.leads',
            'icon' => 'leads',
            'roles' => ['channel_partner'],
            'context' => 'channel_partner',
        ],
        [
            'key' => 'my_applications',
            'label' => 'My applications',
            'route' => 'cp.my-applications',
            'icon' => 'clipboard',
            'roles' => ['channel_partner'],
            'context' => 'channel_partner',
        ],
        [
            'key' => 'profile',
            'label' => 'Profile',
            'route' => 'profile.show',
            'icon' => 'user',
            'roles' => ['channel_partner'],
            'context' => 'channel_partner',
        ],
    ],
];
